id: P010745
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5057
  title: མངོན་པར་རྟོགས་པའི་རྒྱན།
  author: ''
  volumes:
    4c1c3259e94f4a99aea29593b7816540:
      image_group_id: I3CN5059
      title: ''
      volume_number: 1
      total_pages: 40
      base_file: v001.txt
